title: Marina Gardella
description: Postdoctoral fellow at Centre Borelli - ENS Paris-Saclay
site_title: '@marinagardella - Marina Gardella'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: marigardella
email: marigardella@gmail.com
twitter_username: GardellaMarina


# absolute or relative
profile_picture: assets/images/photo.jpg

# Google Analytics ID
google_analytics: 
